sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zhuzm0212.
  alioss:
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1brOZ8gaOIXv3nXbu1GTUzy6Pd7
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    password: zhuzm0212.
    database: 0